### PR TITLE
fncs_goss_bridge to output dictionary for measurements

### PR DESCRIPTION
**Pull request by craig8**
Fixes GRIDAPPSD/GOSS-GRIDAPPS-D#1076 for the 2019-09.0 release.

This should be released with the https://github.com/GRIDAPPSD/gridappsd-python/pull/25 and the sensor service update TBD later tonight

```
//Old Format
{
                "measurements": [{
                                "measurement_mrid": "_00125ca3-12ca-4b8b-a148-c60e03aa7f9f",
                                "magnitude": 78103.82848323896,
                                "angle": -99.22044324389712
                }, {
                                "measurement_mrid": "_0032c3cd-5dec-4944-b1bc-b97b3ec646fc",
                                "magnitude": 2284.5940488360206,
                                "angle": -2.8059748340329578
                }]
}


//New format
{
                "measurements": {
                                "_00125ca3-12ca-4b8b-a148-c60e03aa7f9f": {
                                                "measurement_mrid": "_00125ca3-12ca-4b8b-a148-c60e03aa7f9f",
                                                "magnitude": 78103.82848323896,
                                                "angle": -99.22044324389712
                                },
                                "_0032c3cd-5dec-4944-b1bc-b97b3ec646fc": {
                                                "measurement_mrid": "_0032c3cd-5dec-4944-b1bc-b97b3ec646fc",
                                                "magnitude": 2284.5940488360206,
                                                "angle": -2.8059748340329578
                                }
                }
}
```

Things that need to be coordinated with this schema change

- [x] Viz
- [ ] Proven
- [ ] Apps

### CODE REVIEW

**Comment by afisher1** [comment]
This change will perform the desired schema change for simulation output messages. However, this schema change will break all current applications and services that are reading the simulation output including vizualization and proven ingestion.

I recommend that we need a coordinated pull request for at least the viz and proven to be made for this PR so that we can properly test the platform will function fully with this schema change.

**Comment by poorva1209** [comment]
**DO NOT MERGE THIS UNTIL PROVEN AND VIZ CHANGES ARE DONE**
This is a breaking change for platform as well as applications.

**Comment by craig8** [comment]
@poorva1209  there is still an error with proven on this, however the viz pull request works as expected.  I have not merged the viz into develop yet...as soon as Eric gets the Proven change finished I will merge all 3.
@ericstephan

**Comment by ericstephan** [comment]
Craig,

Did you see this error in the Debug environment on Eclipse or only in the Docker container?

I will look into this later this afternoon and will be at the working meeting.  I am hoping that with Craig on the road I can work with Tonya on the tests.

**Comment by ericstephan** [comment]
The fncs_goss_bridge.py file in Craig’s branch (Andy F. sent me this link below) needs to be used with the gridapps-d docker.   When I use the fncs file from Craig’s branch the simulation runs and reports results.


https://raw.githubusercontent.com/craig8/GOSS-GridAPPS-D/1076-fncs-goss-dictionary-measurement/services/fncsgossbridge/service/fncs_goss_bridge.py

Eric

**Pull request merged**
