### PR TITLE
using class=2 to avoid triplexing low-voltage three-phase loads

### PR DESCRIPTION
**Pull request by temcdrm**
# Description

Prevent secondary phase (s1, s2) assignment on three-phase secondary nodes of the R2 feeder  #1175.

### CODE REVIEW

**Comment by temcdrm** [comment]
Updated with v1.2.17; this version of opendsscmd links dynamically with HELICS.  The platform isn't attempting to use this yet.

**Comment by temcdrm** [comment]
This needs to be merged for HELICS to run OpenDSS as a simulator

**Comment by tonya1** [comment]
@temcdrm   I'm not sure what I need to do.  How can I help test this and approve?  Is this a request to update opendsscmd in the gridappsd container?

**Comment by temcdrm** [comment]
Yes, you can just merge this to update the opendsscmd used in the gridappsd container.

**Pull request merged**
