### PR TITLE
initial commit of state estimator

### PR DESCRIPTION
**Pull request by areiman**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/384%23issuecomment-355364903%22%2C%20%22https%3A//github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/384%23issuecomment-355365812%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/384%23issuecomment-355364903%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22The%20build.bat%20is%20obviously%20for%20a%20windows%20build.%20%20I%20am%20uncertain%20that%20this%20is%20a%20cross%20compiled%20thing.%20%20Why%20is%20build.exe%20in%20the%20repository%3F%20Is%20that%20something%20needed%20to%20build%20or%20an%20output%3F%20%20Please%20add%20a%20build.sh%20for%20a%20linux%20build%20as%20that%20is%20the%20environment%20that%20we%20will%20have%20the%20docker%20images%20be%20built%20under.%22%2C%20%22created_at%22%3A%20%222018-01-04T18%3A46%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/3979063%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/craig8%22%7D%7D%2C%20%7B%22body%22%3A%20%22Also%20it%27s%20better%20practice%20to%20not%20use%20your%20master%20branch%20but%20a%20named%20branch...so%20for%20this%20if%20you%20did%20a%20%5Cr%5Cn%5Cr%5Cn%60%60%60%60%20%5Cr%5Cn%20%20%20%20%23%20Assumes%20you%20are%20on%20the%20master%20branch%20of%20your%20cloned%20repository%20and%20that%20the%20master%20branch%20has%5Cr%5Cn%20%20%20%20%23%20been%20updated%20from%20the%20main%20gridappsd%20repo.%5Cr%5Cn%20%20%20%20git%20checkout%20-b%20feature/state-estimator-service%5Cr%5Cn%60%60%60%60%5Cr%5Cn%5Cr%5CnThis%20would%20create%20a%20new%20branch%20%28from%20the%20existing%20checked%20out%20branch%29%20and%20name%20it%20feature/state-estimator-service.%22%2C%20%22created_at%22%3A%20%222018-01-04T18%3A50%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/3979063%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/craig8%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/384#issuecomment-355364903'>General Comment</a></b>
- <a href='https://github.com/craig8'></a> The build.bat is obviously for a windows build.  I am uncertain that this is a cross compiled thing.  Why is build.exe in the repository? Is that something needed to build or an output?  Please add a build.sh for a linux build as that is the environment that we will have the docker images be built under.
- <a href='https://github.com/craig8'></a> Also it's better practice to not use your master branch but a named branch...so for this if you did a
````
# Assumes you are on the master branch of your cloned repository and that the master branch has
# been updated from the main gridappsd repo.
git checkout -b feature/state-estimator-service
````
This would create a new branch (from the existing checked out branch) and name it feature/state-estimator-service.

<a href='https://www.codereviewhub.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/384?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/384?approve=1'></a>&nbsp;<a href='https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/384'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by craig8** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/384'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by craig8** [comment]
The build.bat is obviously for a windows build.  I am uncertain that this is a cross compiled thing.  Why is build.exe in the repository? Is that something needed to build or an output?  Please add a build.sh for a linux build as that is the environment that we will have the docker images be built under.

**Comment by craig8** [comment]
Also it's better practice to not use your master branch but a named branch...so for this if you did a 

```` 
    # Assumes you are on the master branch of your cloned repository and that the master branch has
    # been updated from the main gridappsd repo.
    git checkout -b feature/state-estimator-service
````

This would create a new branch (from the existing checked out branch) and name it feature/state-estimator-service.

**Comment by poorva1209** [comment]
Closing this pull request without merging until we create C++ wrapper for state estimator.
Also, we may not need the whole source code and dependencies included under services.

**Pull request closed without merging**
